# Build settings
name: Rob Bos
markdown: kramdown
site.baseurl: "devopsjournal.io"
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-paginate 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/mastodon_webfinger
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
  enabled: 
    - year
    - month
    - tags
  layout:
    year: year.html
    tag:  tags.html
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
tag_archive:
  type: liquid
  path: /tags/
mastodon:
  username: https://mstdn.social/@Rob_Bos
  instance: rob@devopsjournal.io
