# Build settings
name: Rob Bos
title: DevOps Journal
url: https://devopsjournal.io
description: "Blog about GitHub, GitHub Actions, Azure DevOps, and supply chain security by Rob Bos"
author: Rob Bos
logo: /images/rob_photo.png
twitter:
  username: robbos81
  card: summary_large_image
social:
  name: Rob Bos
  links:
    - https://twitter.com/robbos81
    - https://github.com/rajbos
    - https://mstdn.social/@Rob_Bos
    - https://sessionize.com/RobBos
markdown: kramdown
site.baseurl: "devopsjournal.io"
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-paginate 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/mastodon_webfinger
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
  enabled: 
    - year
    - month
    - tags
  layout:
    year: year.html
    tag:  tags.html
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
tag_archive:
  type: liquid
  path: /tags/
mastodon:
  username: https://mstdn.social/@Rob_Bos
  instance: rob@devopsjournal.io
